consul:
  image: qnib/consul
  ports:
   - "8500:8500"
  environment:
  - DC_NAME=dc1
  - CONSUL_BOOTSTRAP=true
  dns: 127.0.0.1
  hostname: consul
  container_name: consul
  privileged: true

carbon:
  image: qnib/carbon:sensu
  ports: 
  - "2003:2003"
  environment:
  - DC_NAME=dc1
  - FORWARD_TO_LOGSTASH=true
  - CNT_TYPE=service
  dns: 127.0.0.1
  hostname: carbon
  container_name: carbon

